### PR TITLE
Double Hull changed to SEA 5.0

### PR DESCRIPTION
**Pull request by hamid17amu**

### CODE REVIEW

**Review by pnijhara — CHANGES_REQUESTED** [review]
Why did you resize the images?

**Comment by hamid17amu** [comment]
I was told to do so...

**Comment by hamid17amu** [comment]
yes, I did.

**Comment by pnijhara** [comment]
So it is a good practice to always attach the expected output screenshot. Are you getting the expected output based on your changes?
Also, it is not a good practice to close the PR in the middle of a coversation.

**Pull request closed without merging**
